changelog:
  exclude:
    labels:
      - "changelog: none"
    authors:
      - dependabot[bot]
  categories:
    - title: Fixes 🛠
      labels:
        - "changelog: fix"
        - "type: bug"
    - title: New Features 🎉
      labels:
        - "changelog: add"
        - "type: enhancement"
    - title: Updated
      labels:
        - "changelog: update"
    - title: Tweaked
      labels:
        - "changelog: tweak"
        - "type: technical debt"
    - title: Other Changes
      labels:
        - "*"