changelog:
  exclude:
    labels:
      - no-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Fixes 🛠
      labels:
        - changelog-fix
        - "type: bug"
    - title: New Features 🎉
      labels:
        - changelog-add
        - "type: enhancement"
    - title: Tweaks
      labels:
        - changelog-tweak
        - "type: technical debt"
    - title: Updates
      labels:
        - changelog-update
    - title: Other Changes
      labels:
        - "*"