name: Add Branch Type Label

on:
  pull_request:
    types: opened

jobs:
  SetLabels:
    runs-on: ubuntu-latest
    steps:
      - uses: woocommerce/grow/github-actions/branch-label@add/label-action